/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Donstereo (https://sketchfab.com/Donstereo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grand-theft-auto-san-andreas-grove-street-4dbdbe00c5cf46d8a2ef220045f58d9b
Title: Grand theft auto San Andreas | Grove street
*/
import {socket} from './SocketManager'
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Groove(props) {
  const { nodes, materials } = useGLTF(
    "/grand_theft_auto_san_andreas__grove_street.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="grove_street_0" position={[0, 0.5, 0]} scale={1}>
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.color}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.color}
          // color={"red"}/
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.color}
          
        />
      </group>
    </group>
  );
}

useGLTF.preload("/grand_theft_auto_san_andreas__grove_street.glb");
